extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
plugins:
  - 'react'
  - 'prettier'
  - '@typescript-eslint'
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
